<?php

use Drupal\language\Plugin\LanguageNegotiation\LanguageNegotiationUrl;
use Drupal\Core\Entity\Element\EntityAutocomplete;
use Drupal\Core\Form\FormStateInterface;
use Drupal\finto_taxonomy\TaxonomyHelper;
use Drupal\finto_taxonomy\Controller\FintoAutocompleteController;
use Drupal\finto_taxonomy\Element\EntityAutocomplete as FintoEntityAutocomplete;

use Drupal\finto_taxonomy\Plugin\LanguageNegotiation\AutoCompleteRoute;

function finto_taxonomy_field_widget_form_alter(array &$parent, FormStateInterface $form_state, $context) {
  // Autocomplete widget wraps the actual widgets inside a redundant array.
  if (empty($parent['target_id'])) {
    return;
  }

  if (TaxonomyHelper::elementAllowsFintoAutocomplete($parent['target_id'])) {
    $finto_vid = 'finto';
    $parent['target_id']['#type'] = 'finto_taxonomy_autocomplete';

    $finto_tids = [];

    foreach ($parent['target_id']['#default_value'] as $term) {
      if ($term->getVocabularyId() == $finto_vid) {
        $finto_tids[] = $term->id();
      }
    }

    $parent['target_id']['#attributes']['data-finto_taxonomy-terms'] = implode(',', $finto_tids);
  }
}

function finto_taxonomy_language_negotiation_info_alter(&$negotiation_info) {
  $method_id = LanguageNegotiationUrl::METHOD_ID;
  $negotiation_info[$method_id]['class'] = AutoCompleteRoute::class;
}
